# Generated by Django 3.0.8 on 2020-08-03 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('no_of_contestant', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('voted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=32)),
                ('firstname', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('no_of_votes', models.IntegerField(default=0)),
                ('contesting_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Position')),
            ],
        ),
    ]
