# Generated by Django 3.0.8 on 2020-08-03 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='position',
        ),
    ]
