# Generated by Django 3.0.8 on 2020-08-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20200804_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestant',
            old_name='contesting_for',
            new_name='position',
        ),
    ]
